config/routes.rb
Rails.application.routes.draw do

 	root to: 'welcome#index'

	post '/users', to: 'users#create'

	get '/instructors', to: 'instructors#index'

	get '/bootcamps/:id', to: 'bootcamps#show', as: "bootcamps"

	get '/bootcamps/:id/review', to: 'reviews#new'

	post '/reviews', to: 'reviews#create'

	get  '/reviews', to: 'reviews#show'

	get "/sign_in", to: "sessions#new"

	post "/sessions", to: "sessions#create"

	delete '/sessions', to: 'sessions#destroy'

	get "/users/:id", to: "users#show"

	get "/bootcamp_reviews/:id/edit", to: "bootcamp_reviews#edit", as: "bootcamp_review"

	patch "/bootcamp_reviews/:id/edit", to: "bootcamp_reviews#update"

	get '/bootcamp_reviews/:id', to: "bootcamp_reviews#index"

	get '/bootcamp_review/:id', to: "bootcamp_reviews#show"

end

app/models/instructor.rb
class Instructor < ActiveRecord::Base

	has_many :instructor_reviews
	belongs_to :bootcamp

end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  def index
    @instructors = Instructor.search(params[:search])
  end

  def new
  end

  def create
  end

  def show
    @instructor = instructors.find(params[:id])
      if current_instructor == @instructor
        render :show
      else
        redirect_to "/instructors/new"
      end
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/views/instructors/create.html.erb
<h1>Isntructors#create</h1>
<p>Find me in app/views/isntructors/create.html.erb</p>

app/views/instructors/destroy.html.erb
<h1>Isntructors#destroy</h1>
<p>Find me in app/views/isntructors/destroy.html.erb</p>

app/views/instructors/edit.html.erb
<h1>Isntructors#edit</h1>
<p>Find me in app/views/isntructors/edit.html.erb</p>

app/views/instructors/index.html.erb
<h1>Isntructors#index</h1>
<p>Find me in app/views/isntructors/index.html.erb</p>

<% form_tag instructor_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<%end>

app/views/instructors/new.html.erb
<h1>Isntructors#new</h1>
<p>Find me in app/views/isntructors/new.html.erb</p>

app/views/instructors/show.html.erb
<h1>Isntructors#show</h1>
<p>Find me in app/views/isntructors/show.html.erb</p>

app/views/instructors/update.html.erb
<h1>Isntructors#update</h1>
<p>Find me in app/views/isntructors/update.html.erb</p>