config/routes.rb
Rails.application.routes.draw do

 	root to: 'welcome#index'

	post '/users', to: 'users#create'

	get '/instructors', to: 'instructors#index'

	get '/bootcamps/:id', to: 'bootcamps#show', as: "bootcamps"

	get '/bootcamps/:id/review', to: 'reviews#new'

	post '/reviews', to: 'reviews#create'

	get  '/reviews', to: 'reviews#show'

	get "/sign_in", to: "sessions#new"

	post "/sessions", to: "sessions#create"

	delete '/sessions', to: 'sessions#destroy'

	get "/users/:id", to: "users#show"

	get "/bootcamp_reviews/:id/edit", to: "bootcamp_reviews#edit", as: "bootcamp_review"

	patch "/bootcamp_reviews/:id/edit", to: "bootcamp_reviews#update"

	get '/bootcamp_reviews/:id', to: "bootcamp_reviews#index"

	get '/bootcamp_review/:id', to: "bootcamp_reviews#show"

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@user = User.new
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<head>
    <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>

</head>
<body class="home_body">
    <%= render 'partials/nav_home' %>
    <%= render 'partials/login_modal' %>
    <%= render 'partials/signup_modal' %>
    
        <div class="blurb_div">
            <p class="css_text">View, find, and review the</p>
            <p class="css_text"> best bootcamp for you!<span class="typing_span">|</span></p>
        </div>

        <input type="text" placeholder="Search For Your Bootcamp" class="search" onkeydown="search(this)"/>
        
    <div class="menu-wrap">
        <nav class="menu">
            <ul class="clearfix">
                <li>
                    <a class="dropdown_header" href="#">Or Search the List<span class="arrow">&#9660;</span></a>
                      <ul class="sub-menu">
                        <li data-no-turbolink="true"><%= link_to "Academy X", bootcamps_path(5) %></li>
                        <li data-no-turbolink="true"><%= link_to "Anyone Can Learn to Code", bootcamps_path(6) %></li>
                        <li data-no-turbolink="true"><%= link_to "App Accademy", bootcamps_path(7) %></li>
                        <li data-no-turbolink="true"><%= link_to "Apprentice.io", bootcamps_path(8) %></li>
                        <li data-no-turbolink="true"><%= link_to "Big Nerd Ranch", bootcamps_path(9) %></li>
                        <li data-no-turbolink="true"><%= link_to "CodePath", bootcamps_path(10) %></li>
                        <li data-no-turbolink="true"><%= link_to "Coder Camps", bootcamps_path(11) %></li>
                        <li data-no-turbolink="true"><%= link_to "CodeStream Labs", bootcamps_path(12) %></li>
                        <li data-no-turbolink="true"><%= link_to "Codify Academy", bootcamps_path(13) %></li>
                        <li data-no-turbolink="true"><%= link_to "Coding Dojo", bootcamps_path(14) %></li>
                        <li data-no-turbolink="true"><%= link_to "Dev Bootcamp", bootcamps_path(15) %></li>
                        <li data-no-turbolink="true"><%= link_to "Fire Bootcamp", bootcamps_path(16) %></li>
                        <li data-no-turbolink="true"><%= link_to "Galvanize", bootcamps_path(17) %></li>
                        <li data-no-turbolink="true"><%= link_to "General Assembly", bootcamps_path(3) %></li>
                        <li data-no-turbolink="true"><%= link_to "Hack Reactor", bootcamps_path(4) %></li>
                        <li data-no-turbolink="true"><%= link_to "Hackbright Academy", bootcamps_path(18) %></li>
                        <li data-no-turbolink="true"><%= link_to "Hacker Coding Academy", bootcamps_path(19) %></li>
                        <li data-no-turbolink="true"><%= link_to "Hackership San Francisco", bootcamps_path(20) %></li>
                        <li data-no-turbolink="true"><%= link_to "LearnTech Labs", bootcamps_path(21) %></li>
                        <li data-no-turbolink="true"><%= link_to "Make School", bootcamps_path(22) %></li>
                        <li data-no-turbolink="true"><%= link_to "MakerSquare", bootcamps_path(23) %></li>
                        <li data-no-turbolink="true"><%= link_to "Metis", bootcamps_path(24) %></li>
                        <li data-no-turbolink="true"><%= link_to "Mobile Makers Academy", bootcamps_path(25) %></li>
                        <li data-no-turbolink="true"><%= link_to "Product School", bootcamps_path(26) %></li>
                        <li data-no-turbolink="true"><%= link_to "Thinkful", bootcamps_path(27) %></li>
                        <li data-no-turbolink="true"><%= link_to "Tradecraft", bootcamps_path(28) %></li>
                        <li data-no-turbolink="true"><%= link_to "Zipfian Academy", bootcamps_path(29) %></li>
                    </ul>
                </li>

            </ul>
        </nav>
    </div>

</body>